language: java
jdk:
  - oraclejdk8
sudo: required
services:
    - docker
addons:
  apt:
    packages:
      - oracle-java8-installer
script:
  - mvn pmd:check
  - sudo docker-compose up --abort-on-container-exit web-build
