version: '2'
services:
  db:
    image: postgres
    ports:
      - "1234:5432"
    environment:
      - POSTGRES_USER=director
      - POSTGRES_DB=kordsch
      - POSTGRES_PASSWORD=minfin
  web:
    build: .
    volumes:
      - ./build:/usr/src/app/target
    links:
      - db
