version: '2'
services:
  db:
    image: postgres
    ports:
      - "1234:5432"
    environment:
      - POSTGRES_USER=director
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=minfin
  web:
    build: .
    ports:
      - "8082:8080"
    volumes:
    - ./build:./target
    links:
      - db
