version: '2'
services:
  db:
    image: postgres
    ports:
      - "1234:5432"
    environment:
      - POSTGRES_USER=director
      - POSTGRES_DB=kordsch
      - POSTGRES_PASSWORD=minfin
  web-build:
    build: .
    volumes:
      - ./target:/usr/src/app/target
    links:
      - db
      - logstash
    environment:
      - ACTION=build

  web-run:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - ./target:/usr/src/app/target
    links:
      - db
      - logstash
      - kibana
    environment:
      - ACTION=run

  elasticsearch:
    image: elasticsearch
    expose:
     - "9200"
     - "9300"

  logstash:
    image: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
     - ./logstash_conf:/etc/logstash/conf.d
    expose:
     - "5000"
    links:
     - elasticsearch

  kibana:
    image: kibana
    environment:
       - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
     - "5602:5601"
    links:
     - elasticsearch
